name: CI

on:
  [push]

jobs:
  scan:
    uses: ./.github/workflows/security-scan.yml
    with: 
      image-name: "myapp"
      registry: "ghcr.io/yourhandle"
    permissions:
      contents: read
      
